Netrunnerdb\CardsBundle\Entity\Faction:
    type: entity
    table: faction
    repositoryClass: Netrunnerdb\CardsBundle\Repository\FactionRepository
    gedmo:
        translation:
            locale: locale
    indexes:
        code_index:
            columns: [ code ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: faction
        decklists:
            targetEntity: Netrunnerdb\BuilderBundle\Entity\Decklist
            mappedBy: faction
    manyToOne:
        side:
            targetEntity: Side
            inversedBy: factions
            joinColumn:
                name: side_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
        name:
            type: string
            length: 255
            gedmo:
                - translatable
        color:
            type: string
            length: 6
        isMini:
            type: boolean
            nullable: true
            column: is_mini
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
