AppBundle\Entity\Pack:
    type: entity
    table: pack
    repositoryClass: AppBundle\Repository\PackRepository
    gedmo:
        translation:
            locale: locale
    indexes:
        date_release_index:
            columns: [ date_release ]
        position_index:
            columns: [ position ]
    manyToOne:
        cycle:
            targetEntity: Cycle
            inversedBy: packs
            joinColumn:
                name: cycle_id
                referencedColumnName: id
    oneToMany:
        cards:
            orderBy: { 'position': 'ASC' }
            targetEntity: Card
            mappedBy: pack
            fetch: EXTRA_LAZY
        decklists:
            targetEntity: Decklist
            mappedBy: lastPack
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            unique: true
            length: 10
        name:
            type: string
            length: 255
            gedmo:
                - translatable
        dateRelease:
            type: date
            nullable: true
            column: date_release
        size:
            type: smallint
            nullable: true
        ffgId:
            type: integer
            column: ffg_id
            nullable: true
        position:
            type: smallint
            nullable: false
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
