AppBundle\Entity\Type:
    type: entity
    table: type
    repositoryClass: AppBundle\Repository\TypeRepository
    gedmo:
        translation:
            locale: locale
    indexes:
        name_index:
            columns: [ name ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: type
    manyToOne:
        side:
            targetEntity: Side
            joinColumn:
                name: side_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            unique: true
            length: 10
        name:
            type: string
            length: 255
            gedmo:
                - translatable
        position:
            type: integer
            nullable: false
        isSubtype:
            type: boolean
            nullable: true
            column: is_subtype
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
